### ISSUE TITLE
Add option to avoid computing exact objective at end of optimization

### ISSUE THREAD

**Issue by rcurtin** [mlpack/ensmallen#108]
At the end of most of the SGD-like optimizers, we have a loop that loops over all parts of the decomposable function and computes the final objective.  But this is problematic in that the decomposable function could have *very many* functions, meaning that the final objective computation takes a very long time.  This could easily be seen with, e.g., training a machine learning model, where you might take 20 passes over the data and each pass could take an hour or more.  Computing the exact final objective is equivalent to one additional pass over the data.

To solve this, we could add an extra parameter to each of our decomposable function optimizers: `exactObjective`.  If `exactObjective` is true, then the final objective will be computed exactly, just like it is now.  If it's false (which should be the default), then just the estimate of the final objective obtained on the last pass over the data will be used.

In general, only estimates of the final objective function are given back by all deep learning toolkits and machine learning optimization toolkits I have encountered.  So computing the exact objective every time is basically just a computation disadvantage for us, and although it can be useful, we should allow the user to specify whether they want it (and assume that they don't, to match what others are doing).

**Comment by SinaMojtahedi** [comment]
Dear all,
Lets consider a system of equations are as below:
((1-x(1))(10+x(5)))^2/(((x(1)^2)x(3)^2)+((1-x(1))^2x(2)^2)) = 0.154;
((1-x(1))(10-x(5)))^2/(((x(1)^2)x(3)^2)+((1-x(1))^2x(2)^2)) = 0.254;
(x(1)(10+x(4)))^2/(((x(1)^2)x(3)^2)+((1-x(1))^2x(2)^2)) = 0.545;
(x(1)(10-x(4)))^2/(((x(1)^2)x(3)^2)+((1-x(1))^2x(2)^2)) = 0.034;
(10+(x(1)*x(4))+(1-x(1))*x(5))^2/(((x(1)^2)x(3)^2)+((1-x(1))^2x(2)^2)) = 0.994;
(10-(x(1)*x(4))-(1-x(1))x(5))^2/(((x(1)^2)x(3)^2)+((1-x(1))^2x(2)^2)) = 0.063;
and I want to find x(1) ... x(5) values so that the equalities hold.
I already tried so many optimization methods but the problem is, after finding the values when I replace them with x values the error values I came across are very large. That is if we consider for example
((1-x(1))(10+x(5)))^2/(((x(1)^2)x(3)^2)+((1-x(1))^2x(2)^2)) = A then A is different than 0.154 (the difference must be at most 0.01 but it turns to be 0.3 for example and this is true for all the 6 equations)
Any help (MATLAB, PYTHON) is appreciated.
Best,

**Comment by rcurtin** [comment]
Fixed with #109.
