### ISSUE TITLE
DE: need for DecomposableFunction not stated in documentation

### ISSUE THREAD

**Issue by ElianeBriand** [mlpack/ensmallen#144]
#### Description of problem

The differential evolution algorithm is documented as needing an arbitrary function, both in the function type and optimizer section of the documentation.

However, using the code in the master branch (commit 9b730c7), the DE algorithm need a NonDifferentiableDecomposableFunctionType according to the static_assert error message.

In addition to the discrepancy between documentation and code, the static_assert error message speaks of decomposable function, but the documentation use the term separable function only. These terms are synonyms, but this may not be obvious to the user. If you ctrl+F in the documentation for decomposable, there is no result, which is unfortunate because it make fixing error in one's code more difficult. I suggest either saying the function need to be separable in the static_assert message, or mentioning the term decomposable function in the documentation.

#### Problem location
http://ensmallen.org/docs.html

doc/functions_types.md
doc/optimizers.md

**Comment by rcurtin** [comment]
Hey @ElianeBriand, thanks for the clear bug report---it made my job easy.  It turns out DE actually should work with arbitrary functions, not arbitrary separable functions.  So I fixed the check in that code.

Also, you are right, we should definitely have documentation whose terms match the error messages.  That was an artifact from early ensmallen development when we hadn't settled on the terms to use yet. :(

I opened #145 which fixes both of these issues; now, error messages will use the terms `separable` and `arbitrary`.

Thanks for pointing out the issue! :+1:

**Comment by ElianeBriand** [comment]
Thanks for the fix. And thanks for maintaining this library, it's really one of the best and easier to user optimization libs available in C++.

**Comment by rcurtin** [comment]
Great to hear that, thanks! :+1:

**Comment by rcurtin** [comment]
I released ensmallen 2.10.5 today with these documentation fixes.  Thanks again for the report!
