### ISSUE TITLE
SimpleAdaDeltaTestFunctionFMat Failing

### ISSUE THREAD

**Issue by codeboy5** [mlpack/ensmallen#182]
#### Steps to reproduce

Just Run The Ensmallen Test Suite

#### Expected behavior

The Test Should Pass.

#### Actual behavior

<img width="747" alt="Screenshot 2020-03-18 at 7 52 29 PM" src="https://user-images.githubusercontent.com/40931412/76970507-01674000-6952-11ea-9041-6fbd0e5003ef.png">

I would like to work on this issue, if everyone is experiencing this.

**Comment by zoq** [comment]
Often this is because we don't use enough iterations or use a to small step size. What we often do is uncomment: 
https://github.com/mlpack/ensmallen/blob/3cb382767108886e942d50d961815bc6310a329a/tests/main.cpp#L20-L27

and run the test for multiple iterations, https://github.com/mlpack/mlpack/issues/922 does have some more information. Maybe you can do that and figure out how often the test fails?

**Comment by codeboy5** [comment]
Okay, that sounds good.I will try that.
