### ISSUE TITLE
Constrained function optimization failed

### ISSUE THREAD

**Issue by JJR1234** [mlpack/ensmallen#199]
#### Issue description
I'm trying to optimize a simple quadratic function (x-beta)^2 with simple constraints: beta(0) > 0. And, I used the ens::AugLagrangian optimizer for that, but the results produce NaN. 

#### Your environment

 * version of ensmallen: ensmallen 2.12.1
 * operating system: Mac
 * compiler: Xcode/c++
 * version of Armadillo: Armadillo 9.870.2
 * any other environment information you think is relevant:

#### Steps to reproduce
#include <ensmallen.hpp>

class TestConstraint
{
public:
    // Construct the object with the given the design 
    // matrix and responses.
    TestConstraint(const arma::mat& X) :
    X(X) { }
    
    // Return the objective function for model parameters beta.
    double Evaluate(const arma::mat& beta)
    {
        return arma::accu(arma::square(X-beta));
    }
    
    // Compute the gradient for model parameters beta
    void Gradient(const arma::mat& beta, arma::mat& g)
    {
        g = -2 *(X - beta);
    }
    
    size_t NumConstraints() {
        return 1;
    }
    
    double EvaluateConstraint(const size_t i, const arma::mat& beta){
        if(beta(i,0)>0){
            return 0;
        }else{
            return DBL_MAX;
        }
    }
    
    void GradientConstraint(const size_t i, const arma::mat& beta, 
                            arma::mat& g){
        arma::mat g_tmp(beta.n_rows,beta.n_cols, arma::fill::zeros);
        g = g_tmp;
    }
    
    
private:
    // The design matrix.
    const arma::mat& X;
};

int main() {
    arma::mat x(2,2,arma::fill::ones);
    TestConstraint test(x);
    
    ens::AugLagrangian optfun;
    
    arma::mat beta(x.n_rows, x.n_cols, arma::fill::ones);
    
    // Run the optimization
    optfun.Optimize(test, beta);
    std::cout << beta ;
    
}

#### Expected behavior

The results should return a matrix of all ones.

#### Actual behavior

The retuned results are NaN. As I changed the input x, the results sometime is correct while sometimes are NaN. If the first element of x is negative (where the constraint condition is), the results are always NaN.

**Comment by rcurtin** [comment]
Hey @JJR1234, I'm really sorry this has taken so long to respond to.  It's been hard for me to find the time lately.  I'm able to reproduce your issue, so I will try to keep digging in here and find out what might be going on.  I know that the augmented Lagrangian algorithm can sometimes be hard to tune.

**Comment by rcurtin** [comment]
Ok... I managed to make the code work but I had to modify it in a few ways:

```
#include <ensmallen.hpp>
  
class TestConstraint
{
 public:
  // Construct the object with the given the design
  // matrix and responses.
  TestConstraint(const arma::mat& X) :
  X(X) { }
~~
  // Return the objective function for model parameters beta.
  double Evaluate(const arma::mat& beta)
  {
      return arma::accu(arma::square(X-beta));
  }
~~
  // Compute the gradient for model parameters beta
  void Gradient(const arma::mat& beta, arma::mat& g)
  {
      g = -2 *(X - beta);
  }
~~
  size_t NumConstraints() {
      return 1;
  }
~~
  double EvaluateConstraint(const size_t i, const arma::mat& beta){
      if(beta(i,0)>0){
          return 0;
      }else{
          return beta(i, 0);
      }
  }
~~
  void GradientConstraint(const size_t i, const arma::mat& beta,~
                          arma::mat& g){
      arma::mat g_tmp(beta.n_rows,beta.n_cols, arma::fill::zeros);
      g_tmp[i] = beta(i, 0) > 0 ? 0 : 1;
      g = g_tmp;
  }

 private:
  // The design matrix.
  const arma::mat& X;
};

int main() {
  arma::mat x(2,2,arma::fill::ones);
  TestConstraint test(x);

  ens::AugLagrangian optfun;

  arma::mat beta(x.n_rows, x.n_cols, arma::fill::ones);
  beta *= -1;

  // Run the optimization
  optfun.Optimize(test, beta);
  std::cout << beta ;
}
```

I'm just going to write now what I had to do to make this work, and then tomorrow I'll figure out the right way to actually fix these things:

 - The initial point you were using is actually the optimum.  I changed the code to *not* start from the optimum (it now starts from `[-1 -1; -1 -1]`), because it appears L-BFGS will not terminate when the gradient norm is 0 on the *first* iteration, leading to it taking an infinite step, hence all the NaNs.

 - I changed the constraints to be "soft": they don't take value 0 or `DBL_MAX` now, but instead when a coordinate of `beta` is negative, what's returned is "how far" we are from a feasible solution.  I updated the gradient accordingly.  This is because the augmented Lagrangian method repeatedly applies a higher and higher penalty value on a "modified" objective function, but that "modified" objective function still needs to be differentiable.  I think that this point is not described correctly in the documentation.  I will check tomorrow and figure out how it can be updated if necessary.

Sorry for the problems that you faced!  I hope my message here is helpful (even if it is very late).

**Comment by JJR1234** [comment]
@rcurtin This is great and very helpful. Thank you so much!

**Comment by rcurtin** [comment]
I opened ensmallen#201 to fix the issue.  Thanks again for the report! :+1:

**Comment by zoq** [comment]
WIth #201 merged let's close this one. If you have any other issue don't hesitate to open another issue.
