### ISSUE TITLE
Python bindings for ensmallen?

### ISSUE THREAD

**Issue by AlexPars** [mlpack/ensmallen#212]
Could you please clarify whether there are Python bindings for ensmallen, along the same lines as RCppEnsmallen for R?
While I have looked for such a Python package, I could not locate it.

**Comment by zoq** [comment]
Hello @AlexPars there are no Python bindings for ensmallen, however you could use mlpack which provides Python bindings and internally uses ensmallen.

It should be possible to adapt the mlpack bindings functionality for ensmallen as well, but there are no plans yet.

**Comment by conradsnicta** [comment]
@AlexPars You may want to look at the [carma](https://github.com/RUrlus/carma) project which provides links between Python and [Armadillo](http://arma.sourceforge.net) (the linalg library used by ensmallen), and the [example code](https://github.com/smrfeld/speed-up-python-with-carma) of how to use carma to speed up Python by interfacing with Armadillo-based C++ code.  With that you can indirectly use ensmallen from within Python.

**Comment by conradsnicta** [comment]
@AlexPars You may want to look at the [carma](https://github.com/RUrlus/carma) project which provides links between Python and [Armadillo](http://arma.sourceforge.net) (the linalg library used by ensmallen), and the [example code](https://github.com/smrfeld/speed-up-python-with-carma) of how to use carma to speed up Python by interfacing with Armadillo-based C++ code.  With that you can indirectly use ensmallen from within Python.

CC: @rcurtin

**Comment by AlexPars** [comment]
Thank you for mentioning carma. It appears then that, as of now, I can only call ensmallen indirectly

**Comment by rcurtin** [comment]
For efficiency, ensmallen uses template metaprogramming techniques.  Part of this efficiency comes from the fact that the objective function is also implemented in C++.  So, if we were to provide a Python interface to ensmallen, I'm not sure how we could keep that efficiency in place; the only way I know that we could do this so that a user could specify an objective function in Python is to pass a function pointer---which would disable the compiler from making various optimizations.  While in some cases the overhead would be minimal, it could in other cases be noticeable or even problematic.

I certainly wouldn't be opposed to a project that wrapped ensmallen into Python, although unless some way was found to achieve parity in performance, those wrappers should definitely point users to C++ for efficiency.

(RcppEnsmallen doesn't have this problem because in order to use it, R users actually write C++, which is then compiled into an R function that can be called.)

**Comment by apoorvalal** [comment]
Hi folks, 
I've implemented a very basic pybind11-based wrapper [currently for L-BFGS only, since I want to use it for M-estimation] and it seems to work [reasonably well](https://github.com/apoorvalal/pyensmallen/blob/master/notebooks/example.ipynb) (even with objective functions defined in python with numpy arrays). Just learned about the `carma` project from this thread and might try it out to see if it can be used to define an objective function.

I'd appreciate any feedback or contributions.

**Comment by rcurtin** [comment]
@apoorvalal thanks for the link! pyensmallen looks nice, can you let us know when it is stable and available on PyPI? Then we can link to it from the ensmallen documentation.

I guess that the way that it works is that the ensmallen types are compiled with some wrapper class as the `FunctionType`? so e.g. the compiler will not be able to jointly optimize the optimizer and also the function, since compilation happens when the binding is built?  Or is there a way around that? (I don't think there is, but maybe there is some special way pybind provides that I am not clever enough to know about? 😄)

**Comment by apoorvalal** [comment]
Hi @rcurtin, took me some time to get back to this but `pyensmallen` is now on [pypi](https://pypi.org/project/pyensmallen/). I intend to use it for some econometrics libraries, and the developers behind [optimagic](https://optimagic.readthedocs.io/en/latest/) are also keen on adding support for it.

Thanks again for the excellent library; despite the very bare-bones implementation, I'm still getting major speedups relative to existing scipy machinery.

**Comment by rcurtin** [comment]
Awesome, that is great to hear!  If you are seeing good speedups, you could publicize the effort by getting a table of numbers and submitting to JOSS or something like that.
