### ISSUE TITLE
mlpack bits (logging)

### ISSUE THREAD

**Issue by zoq** [mlpack/ensmallen#3]
In a couple of files we use mlpack's logging capabilities (``Log::Info, Log::Warn``). Are we going to use: ``arma::get_cout_stream()`` and ``arma::get_cerr_stream()``. Any thoughts?

**Comment by conradsnicta** [comment]
Both are fine.  `arma::get_cout_stream()` is probably best suited to "normal" and expected output, such as printing progress (eg. while executing an iterative algorithm). `arma::get_cerr_stream()` is best suited for printing warnings and errors.

Alternatively, we can use `cout` and `cerr` directly.

In combination with either of the options above, it might be useful to adapt the simple printing approach used by armadillo.  Internally, armadillo uses macros such as `arma_debug_print` and `arma_debug_warn`, which can be made inactive by the user by defining `ARMA_DONT_PRINT_ERRORS`.

It's probably not a good idea to directly use `arma_debug_print` and `arma_debug_warn`, as these are internal functions. However, it would be easy to create analogues for ensmallen. For example, `ens_debug_warn`, which use optional defines such as `ENS_DONT_PRINT_ERRORS`.

For all the gory details, see armadillo's [debug.hpp](https://gitlab.com/conradsnicta/armadillo-code/blob/9.200.x/include/armadillo_bits/debug.hpp)

**Comment by rcurtin** [comment]
I think that maybe it might be a good idea here to emulate Armadillo's `get_cout_stream()` and `get_cerr_stream()`, so that we can do in some mlpack header, e.g.,

```
ens::set_cout_stream(Log::Info);
ens::set_cerr_stream(Log::Warn);
```

and then for any `Log::Fatal` call we can just throw an exception.

I think that it won't be quite as simple as that; I'll try and find some time in the next day or two to think about if that will actually work.  Something simple is good for now, but in the longer term this may also be related to mlpack#1481, where the user would pass some functor that would have some behavior when they wanted to print the loss or something like this.

**Comment by rcurtin** [comment]
Actually, looks like I wrote my comment too late. :)  71e6979 seems to handle most of this already.  Still I'll think about how this can be hooked up more nicely to the mlpack infrastructure when desired.  Maybe this?

```
#ifdef ENS_CUSTOM_INFO_LOG
Info = ENS_CUSTOM_INFO_LOG
#endif

#ifdef ENS_CUSTOM_WARN_LOG
Warn = ENS_CUSTOM_WARN_LOG
#endif
```

and then before including ensmallen, mlpack headers can just `#define ENS_CUSTOM_INFO_LOG mlpack::Log::Info` and `#define ENS_CUSTOM_WARN_LOG mlpack::Log::Warn`.  (Also the mlpack header will have to first include the Log headers before including ensmallen, but that shouldn't be an issue---we can control that ordering.)

**Comment by rcurtin** [comment]
@coatless: agreed.  Right now the code just uses Armadillo's output streams so there should be no problem for Rcpp.
