### ISSUE TITLE
ensmallen header

### ISSUE THREAD

**Issue by zoq** [mlpack/ensmallen#52]
The examples on the webpage use ``#include <ensmallen>`` instead of ``#include <ensmallen.hpp>``, but we only provide ``ensmallen.hpp``. So I think we should either adjust the examples or change the name of the header file. I don't have any preference, any thoughts?

**Comment by conradsnicta** [comment]
Since we have released 1.10, we need to maintain backwards compatibility by having `ensmallen.hpp`.

However, the existence of the `ensmallen.hpp` is not mutually exclusive with also having the `ensmallen` header.  I prefer the latter form, as it's shorter and consistent with the naming style used by the standard C++ library.

As such, I suggest that we add the `ensmallen` header, which contains only the following:

    #include <ensmallen.hpp>

**Comment by rcurtin** [comment]
Seems to me like it would just be easiest to update the website.  Using the scripts I already have set up, if we just update all the documentation in `optimizers.md` and `function_types.md`, I can release a new version and the website will automatically get rebuilt.  Any objection to that?

**Comment by conradsnicta** [comment]
ok with me
