### ISSUE TITLE
use Armadillo RNG support

### ISSUE THREAD

**Issue by rcurtin** [mlpack/ensmallen#6]
There are a couple instances where mlpack's `Random()` or `RandInt()` functions are used:

```
./parallel_sgd/parallel_sgd_impl.hpp:          mlpack::math::randGen);
./sa/sa_impl.hpp:  const double unif = 2.0 * math::Random() - 1.0;
./sa/sa_impl.hpp:  const double xi = math::Random();
./scd/descent_policies/random_descent.hpp:    return mlpack::math::RandInt(function.NumFeatures());
```

I think this shows up a lot in the tests too.  Instead, we can use Armadillo's RNG here; so `mlpack::math::randGen` can (probably) be replaced by `arma::arma_rng_cxx11_instance` or something similar, and we can use that to generate random numbers.

However there is also the Armadillo configuration parameter `ARMA_USE_EXTERN_CXX11_RNG`; but, looking through it quickly, I don't see anything different for us to do whether or not someone using ensmallen has written `#define ARMA_USE_EXTERN_CXX11_RNG`.

**Comment by conradsnicta** [comment]
Armadillo has an internal class called `arma_rng_cxx11`, but it's not part of the public API.

The `ARMA_USE_EXTERN_CXX11_RNG` define is set by the armadillo cmake installer to indicate that the `arma::arma_rng_cxx11_instance` is available in the armadillo wrapper library.  The define not meant to be used outside of that specific use case.  Furthermore, it's only valid on Linux systems with gcc 4.8.3+. It currently doesn't work with macOS or windoze.  (it should be trivial to make it work with macOS, now that Apple has proper support for the`thread_local` storage class in C++11).

Perhaps it would be sufficient to simply use the public [randi()](http://arma.sourceforge.net/docs.html#randi), [randu()](http://arma.sourceforge.net/docs.html#randu_randn_standalone), [randn()](http://arma.sourceforge.net/docs.html#randu_randn_standalone) and [randg()](http://arma.sourceforge.net/docs.html#randg) functions ?

In armadillo version 8.400+ all of the above functions were extended to output single scalars.
`randg()` was added in version 4.650.  `randi()` was added in version 3.930.
`randu()` and `randn()` have been available "since forever".

If armadillo 8.400 is "too recent", it's still possible to use the above functions to generate scalars. Simply use `as_scalar()` on a random vector that has only one dimension.

As a sidenote, armadillo 8.400 is available in Ubuntu 16.04.

**Comment by zoq** [comment]
In case of:

```c++
std::shuffle(visitationOrder.begin(), visitationOrder.end(), mlpack::math::randGen);
```

it should be reasonable to use:

```
visitationOrder = arma::shuffel(visitationOrder);
```

any thoughts?

**Comment by zoq** [comment]
For the other cases I agree, it would be simple to use: ``arma::as_scalar(randi(...))``.

**Comment by rcurtin** [comment]
Agreed on both counts---I wonder why we didn't just use `arma::shuffle(visitationOrder)` originally?

**Comment by zoq** [comment]
I guess the benefit is that ``std::shuffel`` works inplace; should be neglectable here.

**Comment by conradsnicta** [comment]
arma:shuffle() should detect aliasing and do an inplace shuffle:
https://gitlab.com/conradsnicta/armadillo-code/blob/9.200.x/include/armadillo_bits/op_shuffle_meat.hpp#L62
https://gitlab.com/conradsnicta/armadillo-code/blob/9.200.x/include/armadillo_bits/op_shuffle_meat.hpp#L129

**Comment by zoq** [comment]
Thanks for the clarification, should have checked first. https://github.com/mlpack/ensmallen/commit/05a8743137de66364a27beb225e01b8d955a7430 implements the modifications.

**Comment by rcurtin** [comment]
I think this one is fully handled now---I see no use of any random object or anything other than Armadillo's existing public random functions.
