### ISSUE TITLE
nested namespaces, non-optimisation functions, scope of tests

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#7]
Many of the original mlpack tests declare the use of a lot of namespaces.  For example:

    using namespace mlpack::optimization;
    using namespace mlpack::optimization::test;
    using namespace mlpack::distribution;
    using namespace mlpack::regression;
    using namespace mlpack::ann;
    using namespace mlpack::cv;

This raises a few questions:
1. Is the intent to have all of the optimisation and related functions available within a flat namespace (ie. only within `ens`), or are nested namespaces going to be kept?  I think the former would keep things simpler for end users, and it wouldn't require much code change -- in `ensmallen.hpp` and within the `ens` namespace, simply do a few `using namespace ens::blah` lines
2. Looking at the test sources, it's not clear what parts of mlpack need to be kept.  For example, is the stuff from `mlpack::distribution` and `mlpack::regression` going to be kept?
3. Are all the tests in the `tests` directory required?  For example, going by the `using namespace` declarations in `cv_test.cpp`, it seems that a good chunk of mlpack is being used and/or tested.

**Comment by rcurtin** [comment]
> Is the intent to have all of the optimisation and related functions available within a flat namespace (ie. only within ens), or are nested namespaces going to be kept?

I think that for ensmallen we can just have `ens` and `ens::test`, the latter of which can hold the stuff in the `problems/` directory.  ensmallen is much smaller scope than mlpack so definitely better to keep it simple in my opinion.

> Looking at the test sources, it's not clear what parts of mlpack need to be kept. For example, is the stuff from mlpack::distribution and mlpack::regression going to be kept?

So, I think that we'll need to port over something like the logistic regression function, since a lot of the optimization tests depend on that, but some of the more crazy stuff like `CNEXORTest` in `cne_test.cpp`, I think we should just remove the test (and leave it in mlpack) instead of trying to port some small part of the neural network framework.

> Are all the tests in the tests directory required? For example, going by the using namespace declarations in cv_test.cpp, it seems that a good chunk of mlpack is being used and/or tested.

Oh, I think you're right, probably `cv_test.cpp` isn't needed at all.  I think my heuristic to find files to port was imperfect, so if a test suite or individual test clearly doesn't have anything to do with ensmallen code I think we should just cut it out.

**Comment by zoq** [comment]
> So, I think that we'll need to port over something like the logistic regression function, since a lot of the optimization tests depend on that, but some of the more crazy stuff like CNEXORTest in cne_test.cpp, I think we should just remove the test (and leave it in mlpack) instead of trying to port some small part of the neural network framework.

Agreed, also the logistic regression function is already ported, see https://github.com/mlpack/ensmallen/commit/4056620043f585193284e3fa30a51aea28fe026c; haven't backported the ``ComputeAccuracy`` method, will do that if we think we need the method as well. Also since the logistic regression function implements all flavours (Evaluate, EvaluateWithGradient, PartialGradient, etc.) I think it makes sense to keep the function.

**Comment by rcurtin** [comment]
For the `LogisticRegressionTest` I've written the following adaptation of the `bigbatch_sgd.cpp` test.  I didn't push it in case @conradsnicta was working on it, but this general "formula" should work for most tests.  I did push the auxiliary file `test_function_tools.hpp` to the `tests_catch/` directory.  Then we can use the following code for `

```
/**
 * Run big-batch SGD using BBS_BB on logistic regression and make sure the
 * results are acceptable.
 */
TEST_CASE("BBSBBLogisticRegressionTest", "[BigBatchSGDTest]")
{
  arma::mat data, testData, shuffledData;
  arma::Row<size_t> responses, testResponses, shuffledResponses;

  LogisticRegressionTestData(data, testData, shuffledData, responses,
      testResponses, shuffledResponses);

  // Now run big-batch SGD with a couple of batch sizes.
  for (size_t batchSize = 30; batchSize < 40; batchSize += 5)
  {
    BBS_BB bbsgd(batchSize, 0.01, 0.1, 6000, 1e-3);
    LogisticRegressionFunction<> lr(shuffledData, shuffledResponses, 0.5);
    arma::mat parameters = lr.GetInitialPoint();

    // Run the optimization.
    bbsgd.Optimize(lr, parameters);

    // Compute the class predictions.
    arma::Row<size_t> labels = arma::conv_to<arma::Row<size_t>>::from((1.0 /
        (1.0 + arma::exp(-parameters(0) -
        parameters.tail_cols(parameters.n_elem - 1) * data))) + 0.5);

    // Ensure that the error is close to zero.
    const double acc = double(arma::accu(labels == responses)) /
        double(labels.n_elem);
    REQUIRE(acc == Approx(100.0).epsilon(0.003)); // 0.3% error tolerance.

    arma::Row<size_t> testLabels = arma::conv_to<arma::Row<size_t>>::from((1.0 /
        (1.0 + arma::exp(-parameters(0) -
        parameters.tail_cols(parameters.n_elem - 1) * testData))) + 0.5);

    const double testAcc = double(arma::accu(testLabels == testResponses)) /
        double(testLabels.n_elem);
    REQUIRE(testAcc == Approx(100.0).epsilon(0.006)); // 0.6% error tolerance.
  }
}
```

However, it's not converging right.  I wonder if I ported `LogisticRegressionTestData()` wrong.  I'll look into that further shortly but I have to leave for now.

**Comment by rcurtin** [comment]
Everything is in either `ens` or `ens::test` now, so I think this is sorted out.
